version: '3.8'

services:

  postgres:
    container_name: odoo-postgres
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  odoo:
    container_name: odoo
    image: odoo:18.0
    environment:
      HOST: postgres
      USER: odoo
      PASSWORD: secret
    depends_on:
      - postgres
    ports:
      - 8069:8069
    volumes:
      - config:/etc/odoo
      - extra-addons:/mnt/extra-addons
      - data:/var/lib/odoo
    restart: always
    links:
     - postgres

volumes:
  postgres-data:
  config:
  extra-addons:
  data:
